### ISSUE TITLE
Implement feedback for landing page

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Cowlytics#6]

**Comment by Basilakis** [comment]
`The analytics dashboard for Stripe based SaaS businesses that doesn't take a call to Brian to cancel.`

This is the best line, ever read.
I really hope you manage to release this and it is not a project that it will get shelved. I am happy to offer any help for free ( Marketing / Product ).

**Comment by jimmybisenius** [comment]
You have my word - it won't get shelved!

We've been busy with [Singlelink v2.1.X](https://singlelink.co), but now that's released so we're onto Cowlytics almost full-time this upcoming week and the following until release (Feb 1-7th).

The front-end is almost entirely done, the back-end is next, followed by testing, and will finish off with some added niceties if we have time. Would love to chat and hear your ideas/feedback - we're want to make this as great as possible before launch!

Thanks for the kind words 😄 

Sending you an email, hope to talk soon.
Jim
